all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    k3s_version: v1.34.1+k3s1
    
k3s_cluster:
  children:
    control_plane:
      hosts:
        k3s-cp-1:
          ansible_host: 192.168.1.180
    
    workers:
      hosts:
        k3s-worker-1:
          ansible_host: 192.168.1.185
        k3s-worker-2:
          ansible_host: 192.168.1.186
        k3s-worker-3:
          ansible_host: 192.168.1.187